/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package desktop;

import root.pow.Power;

public class App {

    public static void main(String[] args) {
        Power power = new Power();

        for (int i = -5; i < 30; ++i) {
            for (int j = -5; j < 10; ++j) {
                if (power.pow(i, j) != Math.pow(i, j)) {
                    if (!(j < 0 && power.pow(i, j) == 1)) {
                        System.out.println("a = " + i + " b = " + j + " Wrong result: " + power.pow(i, j)
                                + " True result: " + Math.pow(i, j));
                    }
                }
            }
        }
    }
}
